### ISSUE TITLE
[ Suggestion ] Live update server info after scan is complete

### ISSUE THREAD

**Issue by DarkReaper231** [vert3xo/mcscan#4]
It could update player lists when the scan finishes. Instead of replacing the player lists, it would be better to just add new players to the player lists if it finds that the player is not already in the database.

This would help to roughly know what all players do play on the server and if the player wasn't online on the first scan, it could add them when it pings the servers after scan.

I am scanning small hostings that have just few servers so the scan always ends in matter of minutes but then I no longer can know what players play there

**Comment by vert3xo** [comment]
Thanks for your suggestions, I'll work on them once I have some time.
