### ISSUE TITLE
[ Bug ] Running docker-compose down and then docker-compose up still results in duplicates

### ISSUE THREAD

**Issue by SolsticeSpectrum** [vert3xo/mcscan#5]
![2022-10-16_22-55](https://user-images.githubusercontent.com/38611351/196057905-33e89dfe-9f0f-45e5-8449-e45b989d4481.png)

It should instead add new servers if it finds any online and ignore existing when composing down and up again
And also add new players to existing player lists

**Comment by SolsticeSpectrum** [comment]
But I gotta admit that I love that I no longer need to rebuild entire docker container just to delete old database

**Comment by SolsticeSpectrum** [comment]
Nvm I am just stupid and since I connected host and port to one single "ip" collumn it didn't work because I forgot to change this line

`err := collection.FindOne(database.Ctx, bson.D{primitive.E{Key: "host", Value: p.Ip}}).Decode(&server)`

to this

`err := collection.FindOne(database.Ctx, bson.D{primitive.E{Key: "ip", Value: p.Ip + ":" + strconv.Itoa(p.Port)}}).Decode(&server)`

**Comment by vert3xo** [comment]
I'm glad it works, it was working for me and I got a bit worried :D
